name: Upload to FTP after Commit

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: FTP Deployer
      uses: sand4rt/ftp-deployer@v1.8
      with:
        sftp: true
        host: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local_folder: ./
        remote_folder: /domains/volkov.media/public_html/
